version: 2
jobs:
  build:
    docker:
    - image: cimg/node:lts
    steps:
    - run:
        command: echo "hello world"
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cimg/node:lts
#     steps:
#       - run: echo \"hello world\"